'use client';

import { useRouter } from 'next/navigation';

export default function HealthDisclaimerPage() {
  const router = useRouter();

  return (
    <main className="grid min-h-dvh place-items-center px-5 py-8">
      <section className="surface-card relative w-full max-w-[760px] overflow-hidden p-7 text-sm text-[color:var(--ink-900)] sm:p-8">
        <h1 className="text-[1.75rem] font-semibold tracking-tight text-[color:var(--ink-900)] sm:text-[2rem]">
          Health Disclaimer
        </h1>

        <div className="mt-6 grid gap-5 text-sm leading-7 text-slate-600">
          <p>
            ZYM AI Coach provides general fitness, nutrition, wellness, and educational information only. It does not provide
            medical advice, diagnosis, treatment, or emergency services, and it does not create a physician-patient,
            therapist-patient, dietitian-patient, or other licensed professional relationship.
          </p>
          <p>
            Any training, recovery, nutrition, or body-composition guidance generated by ZYM AI Coach may be incomplete,
            inaccurate, or unsuitable for your personal circumstances, medical history, medications, injuries, allergies,
            or health conditions. You should use independent judgment and consult a qualified professional before acting on
            guidance that could materially affect your health.
          </p>
          <p>
            If you have an injury, chronic illness, heart condition, diabetes, kidney disease, severe pain, chest pain,
            dizziness, fainting, trouble breathing, neurological symptoms, or any urgent or worsening symptom, stop the
            activity and seek licensed medical care or emergency assistance immediately.
          </p>
          <p>
            Exercise, dietary change, supplementation, and weight-management decisions involve inherent risk. By using ZYM,
            you acknowledge that you remain solely responsible for your own decisions, activity choices, and health outcomes.
            ZYM is not a substitute for individualized medical evaluation or supervision.
          </p>
          <p>
            By creating an account, you confirm that you understand this disclaimer and agree to use ZYM AI Coach only as a
            general informational and motivational tool.
          </p>
        </div>

        <div className="mt-8 flex gap-3">
          <button className="btn btn-primary text-sm" type="button" onClick={() => router.push('/register')}>
            Back to Register
          </button>
          <button className="btn btn-ghost text-sm" type="button" onClick={() => router.push('/login')}>
            Back to Login
          </button>
        </div>
      </section>
    </main>
  );
}
