import 'dotenv/config';
import fs from 'fs/promises';
import path from 'path';
import { getFoundationTable, POSTGRES_FOUNDATION_TABLES, POSTGRES_FOUNDATION_TABLE_NAMES } from '../src/database/postgres-foundation.js';

interface ExportedTableManifest {
  columns: string[];
  file: string;
  rowCount: number;
}

interface ExportManifest {
  exportedAt: string;
  sqlitePath: string;
  tables: Record<string, ExportedTableManifest>;
}

function parseArgs(argv: string[]): Map<string, string> {
  const values = new Map<string, string>();
  for (let index = 0; index < argv.length; index += 1) {
    const current = argv[index];
    if (!current.startsWith('--')) continue;
    const next = argv[index + 1];
    if (!next || next.startsWith('--')) {
      values.set(current, 'true');
      continue;
    }
    values.set(current, next);
    index += 1;
  }
  return values;
}

function defaultInputDir(): string {
  return path.join(process.cwd(), 'data', 'postgres-export');
}

function defaultOutputPath(): string {
  return path.join(defaultInputDir(), 'import.sql');
}

function quoteIdentifier(identifier: string): string {
  return `"${String(identifier).replace(/"/g, '""')}"`;
}

function quoteLiteral(value: string): string {
  return `'${String(value).replace(/'/g, "''")}'`;
}

function normalizeScalarLiteral(value: unknown): string {
  if (value === null || value === undefined) {
    return 'NULL';
  }
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) return 'NULL';
    return String(value);
  }
  if (typeof value === 'boolean') {
    return value ? 'TRUE' : 'FALSE';
  }
  return quoteLiteral(String(value));
}

function formatValue(tableName: string, columnName: string, value: unknown): string {
  getFoundationTable(tableName);
  return normalizeScalarLiteral(value);
}

function buildSequenceResetSql(tableName: string, identityColumn: string): string {
  return [
    `SELECT setval(`,
    `  pg_get_serial_sequence(${quoteLiteral(tableName)}, ${quoteLiteral(identityColumn)}),`,
    `  GREATEST(COALESCE((SELECT MAX(${quoteIdentifier(identityColumn)}) FROM ${quoteIdentifier(tableName)}), 0), 1),`,
    `  COALESCE((SELECT MAX(${quoteIdentifier(identityColumn)}) FROM ${quoteIdentifier(tableName)}), 0) > 0`,
    `);`,
  ].join('\n');
}

async function loadManifest(directory: string): Promise<ExportManifest> {
  const manifestPath = path.join(directory, 'manifest.json');
  const raw = await fs.readFile(manifestPath, 'utf8');
  return JSON.parse(raw) as ExportManifest;
}

async function loadRows(directory: string, fileName: string): Promise<Array<Record<string, unknown>>> {
  const filePath = path.join(directory, fileName);
  const raw = await fs.readFile(filePath, 'utf8');
  return raw
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => JSON.parse(line) as Record<string, unknown>);
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  const inputDir = path.resolve(args.get('--in') || defaultInputDir());
  const outputPath = path.resolve(args.get('--out') || defaultOutputPath());
  const manifest = await loadManifest(inputDir);

  for (const tableName of POSTGRES_FOUNDATION_TABLE_NAMES) {
    if (!manifest.tables[tableName]) {
      throw new Error(`Export manifest is missing table "${tableName}"`);
    }
  }

  const statements: string[] = [
    '-- Generated by server/scripts/generate-postgres-import-sql.ts',
    `-- Source SQLite DB: ${manifest.sqlitePath}`,
    `-- Exported at: ${manifest.exportedAt}`,
    'BEGIN;',
    "SET TIME ZONE 'UTC';",
    `TRUNCATE TABLE ${POSTGRES_FOUNDATION_TABLES.map((table) => quoteIdentifier(table.name)).join(', ')} RESTART IDENTITY CASCADE;`,
    '',
  ];

  for (const table of POSTGRES_FOUNDATION_TABLES) {
    const details = manifest.tables[table.name];
    const rows = await loadRows(inputDir, details.file);
    const columns = details.columns;

    statements.push(`-- ${table.name}: ${rows.length} row(s)`);

    if (rows.length > 0) {
      const columnList = columns.map((column) => quoteIdentifier(column)).join(', ');
      const batchSize = 250;

      for (let index = 0; index < rows.length; index += batchSize) {
        const batch = rows.slice(index, index + batchSize);
        const values = batch.map((row) => {
          const rowValues = columns.map((column) => formatValue(table.name, column, row[column]));
          return `(${rowValues.join(', ')})`;
        });
        statements.push(`INSERT INTO ${quoteIdentifier(table.name)} (${columnList}) VALUES\n${values.join(',\n')};`);
      }
    }

    if (table.identityColumn) {
      statements.push(buildSequenceResetSql(table.name, table.identityColumn));
    }

    statements.push('');
  }

  statements.push('COMMIT;');
  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, statements.join('\n') + '\n', 'utf8');
  console.log(`[postgres-import-sql] wrote ${outputPath}`);
}

main().catch((error) => {
  console.error('[postgres-import-sql] failed:', error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
